// frontend-melaonma/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import { config } from './config';
import * as Dialog from '@radix-ui/react-dialog';

type Prediction =
  | 'Benign'
  | 'Malignant'
  | 'Indeterminate / Benign'
  | 'Indeterminate / Malignant';

enum Classification {
  Benign,
  Malignant,
  IndeterminateBenign,
  IndeterminateMalignant,
}

const getLabelFromClassification = (type: number): Prediction | null => {
  switch (type) {
    case 0: {
      return 'Benign';
    }
    case 1: {
      return 'Malignant';
    }
    case 2: {
      return 'Indeterminate / Benign';
    }
    case 3: {
      return 'Indeterminate / Malignant';
    }
    default: {
      return null;
    }
  }
};

function GitHubIcon() {
  return (
    <svg
      width='38'
      height='38'
      viewBox='0 0 38 38'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <path
        d='M19 2.375C9.81469 2.375 2.375 9.81469 2.375 19C2.375 26.3566 7.13391 32.5702 13.7423 34.773C14.5736 34.9184 14.8853 34.4197 14.8853 33.9833C14.8853 33.5884 14.8645 32.2792 14.8645 30.8869C10.6875 31.6558 9.60687 29.8686 9.27437 28.9334C9.08734 28.4555 8.27688 26.98 7.57031 26.5852C6.98844 26.2734 6.15719 25.5045 7.54953 25.4837C8.85875 25.463 9.79391 26.6891 10.1056 27.1878C11.6019 29.7023 13.9917 28.9958 14.9477 28.5594C15.0931 27.4787 15.5295 26.7514 16.0075 26.3358C12.3084 25.9202 8.44313 24.4862 8.44313 18.1272C8.44313 16.3192 9.08734 14.823 10.1472 13.6592C9.98094 13.2436 9.39906 11.5395 10.3134 9.25359C10.3134 9.25359 11.7058 8.81719 14.8853 10.9577C16.2153 10.5836 17.6284 10.3966 19.0416 10.3966C20.4547 10.3966 21.8678 10.5836 23.1978 10.9577C26.3773 8.79641 27.7697 9.25359 27.7697 9.25359C28.6841 11.5395 28.1022 13.2436 27.9359 13.6592C28.9958 14.823 29.64 16.2984 29.64 18.1272C29.64 24.507 25.7539 25.9202 22.0548 26.3358C22.6575 26.8553 23.177 27.8528 23.177 29.4114C23.177 31.635 23.1562 33.4222 23.1562 33.9833C23.1562 34.4197 23.468 34.9392 24.2992 34.773C27.5996 33.6588 30.4675 31.5377 32.4992 28.7082C34.5309 25.8787 35.6241 22.4834 35.625 19C35.625 9.81469 28.1853 2.375 19 2.375Z'
        fill='white'
      />
    </svg>
  );
}

function CloseIcon() {
  return (
    <svg
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <path
        fill-rule='evenodd'
        clip-rule='evenodd'
        d='M5.29289 5.29289C5.68342 4.90237 6.31658 4.90237 6.70711 5.29289L12 10.5858L17.2929 5.29289C17.6834 4.90237 18.3166 4.90237 18.7071 5.29289C19.0976 5.68342 19.0976 6.31658 18.7071 6.70711L13.4142 12L18.7071 17.2929C19.0976 17.6834 19.0976 18.3166 18.7071 18.7071C18.3166 19.0976 17.6834 19.0976 17.2929 18.7071L12 13.4142L6.70711 18.7071C6.31658 19.0976 5.68342 19.0976 5.29289 18.7071C4.90237 18.3166 4.90237 17.6834 5.29289 17.2929L10.5858 12L5.29289 6.70711C4.90237 6.31658 4.90237 5.68342 5.29289 5.29289Z'
        fill='white'
      />
    </svg>
  );
}

type Case = {
  key: string;
  trueLabel: number;
};

const cases: Case[] = [
  {
    key: 'ISIC_1136887',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_2222766',
    trueLabel: Classification.Malignant,
  },
  {
    key: 'ISIC_2691236',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_3640885',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_5574004',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_6202682',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_6364782',
    trueLabel: Classification.Malignant,
  },
  {
    key: 'ISIC_6929321',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_7239167',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_7288606',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_7365059',
    trueLabel: Classification.IndeterminateMalignant,
  },
  {
    key: 'ISIC_7428145',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_8476601',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_8738186',
    trueLabel: Classification.IndeterminateMalignant,
  },
  {
    key: 'ISIC_8801733',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_8999351',
    trueLabel: Classification.IndeterminateMalignant,
  },
  {
    key: 'ISIC_9182038',
    trueLabel: Classification.Benign,
  },
  {
    key: 'ISIC_9498324',
    trueLabel: Classification.Benign,
  },
  {
    trueLabel: Classification.Benign,
    key: 'ISIC_7727119',
  },
  {
    trueLabel: Classification.IndeterminateBenign,
    key: 'ISIC_1028529',
  },
];

const HOST = 'https://melanoma-static.nbaron.com';

function MelanomaSampleTest({ sampleCase }: { sampleCase: Case }) {
  const src = `${HOST}/${sampleCase.key}.jpg`;

  const [classification, setClassification] = useState<number | null>(null);
  const [confidence, setConfidence] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleTestModel = async () => {
    setIsLoading(true);

    try {
      const response = await fetch(
        `${config.backendURL}/melanoma/predict-url`,
        {
          method: 'POST',
          body: JSON.stringify({ url: src }),
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      const data = await response.json();

      setClassification(data.classification);
      setConfidence(data.confidence);
    } catch (error) {
      console.error('Error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog.Root>
      <Dialog.Trigger asChild>
        <img
          src={src}
          className='cursor-pointer aspect-square bg-gray-700 rounded-sm'
          loading='eager'
        />
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay className='fixed top-0 left-0 right-0 bottom-0 bg-black opacity-30' />
        <Dialog.Content
          aria-describedby={undefined}
          className='px-10 py-10 fixed bg-[#003DC4] min-[400px]:max-w-sm min-[400px]:left-1/2 min-[400px]:-translate-x-1/2 flex flex-col gap-7 top-1/2 left-3 right-3 rounded-2xl text-white -translate-y-1/2'
        >
          <div className='flex items-center justify-between'>
            <Dialog.Title className='text-xl'>
              Actual: {getLabelFromClassification(sampleCase.trueLabel)}{' '}
            </Dialog.Title>
            <Dialog.Close className='outline-none'>
              <CloseIcon />
            </Dialog.Close>
          </div>
          <img className='rounded w-full aspect-square' src={src} />
          <div className='flex flex-col'>
            <p className=''>Prediction:</p>
            {typeof classification === 'number' ? (
              <p>{getLabelFromClassification(classification)}</p>
            ) : (
              <p className='font-semibold'>Start test to get results</p>
            )}
          </div>
          <div className='flex flex-col'>
            <p>Confidence:</p>
            {typeof confidence === 'number' ? (
              <p>{(confidence * 100).toFixed(2)}%</p>
            ) : (
              <p className='font-semibold'>Start test to get results</p>
            )}
          </div>
          <button
            onClick={handleTestModel}
            className='py-3 bg-[#00277C] rounded-2xl'
          >
            {isLoading ? <p>Loading results...</p> : <p>Test model</p>}
          </button>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

/**
 * This is a workaround for cold starts with Cloud Run
 * Instead of waiting for the backend to warm up on the initial request, we can hit the /health endpoint on load
 */
const useWarmBackend = () => {
  const warmBackend = async () => {
    try {
      await fetch(`${config.backendURL}/health`);
    } catch (error) {
      console.error('Error warming backend:', error);
    }
  };

  // Hit it once every minute to keep the backend warm
  useEffect(() => {
    const ONE_MINUTE = 1000 * 60;

    const interval = setInterval(warmBackend, ONE_MINUTE);

    warmBackend();

    return () => clearInterval(interval);
  }, []);
};

function App() {
  useWarmBackend();

  const uploadImagesRef = useRef<HTMLInputElement>(null);

  const [classification, setClassification] = useState<number | null>(null);
  const [confidence, setConfidence] = useState<number | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleUploadImage: React.InputHTMLAttributes<HTMLInputElement>['onChange'] =
    async (event) => {
      if (!event.target.files) return;

      const file = event.target.files?.[0];
      if (!file) return;

      const formData = new FormData();
      formData.append('image', file);

      try {
        setIsLoading(true);
        const endpoint = `${config.backendURL}/melanoma/predict`;

        const response = await fetch(endpoint, {
          method: 'POST',
          body: formData,
        });

        const data = await response.json();

        setClassification(data.classification);
        setConfidence(data.confidence);
        setPreviewUrl(URL.createObjectURL(file));
      } catch (error) {
        console.error('Error:', error);
      } finally {
        setIsLoading(false);
        uploadImagesRef.current!.value = '';
      }
    };

  const handleClickUploadImage = () => {
    uploadImagesRef.current?.click();
  };

  return (
    <div className='mx-7 my-7'>
      <a
        href='https://nbaron.com'
        target='_blank'
        className='text-white text-xl'
      >
        nbaron
      </a>
      <div className='flex flex-col gap-4 mt-16 md:gap-7'>
        <h1 className='text-4xl text-white sm:text-5xl font-semibold sm:text-center md:text-5xl max-w-[800px] !leading-[120%] sm:mx-auto'>
          Detecting Melanoma Skin Cancer Using Machine Learning
        </h1>
        <div className='flex text-white flex-col gap-4 sm:text-center md:text-xl'>
          <p>
            Each year 8,290 people die from Melanoma Skin Cancer
            <a
              className='underline'
              target='_blank'
              href='https://www.aad.org/media/stats-skin-cancer#:~:text=The%20vast%20majority%20of%20skin%20cancer%20deaths%20are%20from%20melanoma.&text=Nearly%2020%20Americans%20die%20from,5%2C430%20men%20and%202%2C860%20women.&text=Research%20indicates%20that%20men%20with,rates%20than%20women%20with%20melanoma.'
            >
              ¹
            </a>
          </p>
          <p>
            When detected early, the 5-year survival rate for Melanoma is 99
            percent
            <a
              className='underline'
              href='https://www.skincancer.org/skin-cancer-information/skin-cancer-facts/'
              target='_blank'
            >
              ²
            </a>
          </p>
        </div>
      </div>
      <input
        type='file'
        accept='image/*'
        className='text-white invisible absolute -z-10 -top-full -left-full'
        ref={uploadImagesRef}
        onChange={handleUploadImage}
      />
      <div className='flex flex-col gap-3 mt-7 items-center'>
        {isLoading && (
          <div className='flex flex-col items-center gap-3 my-2'>
            <div className='loader' />
            <p className='text-white text-lg font-semibold'>
              Loading your prediction. This can take up to a minute...
            </p>
          </div>
        )}
        {classification !== null && confidence !== null ? (
          <>
            <div className='flex flex-col gap-2  w-[440px] text-center'>
              {previewUrl && (
                <img
                  src={previewUrl}
                  className='rounded-lg w-full aspect-square object-cover'
                />
              )}
              <p className='text-white font-bold'>
                Prediction: {getLabelFromClassification(classification)}
              </p>
              <p className='text-white'>
                Confidence: {(confidence * 100).toFixed(2)}%
              </p>
            </div>
            <button
              className='text-white bg-[#00277C] sm:max-w-72 sm:text-md mx-auto w-full py-3 rounded-3xl'
              onClick={handleClickUploadImage}
            >
              Try another
            </button>
          </>
        ) : (
          <button
            className='text-white bg-[#00277C] sm:max-w-72 sm:text-lg mx-auto w-full py-3 rounded-3xl'
            onClick={handleClickUploadImage}
          >
            Upload image
          </button>
        )}

        <p className='text-gray-200 text-left sm:text-center max-w-[400px]'>
          This is for educational purposes only and should not be used as a
          substitute for professional medical care
        </p>
      </div>
      <div className='text-white flex flex-col mt-12 gap-3 lg:mx-36'>
        <div className='flex flex-col gap-3 my-3'>
          <p className='font-medium text-3xl text-center'>
            Test our model using a sample image
          </p>
          <p className='text-center'>
            Test our machine learning model using randomly selected images from
            the{' '}
            <a
              className='underline'
              href='https://isic-archive.com/'
              target='_blank'
            >
              ISIC dataset
            </a>{' '}
          </p>
        </div>
        <div className='grid grid-cols-1 gap-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4'>
          {cases.map((_, index) => {
            const currentCase = cases[index];
            if (!currentCase) return null;

            return <MelanomaSampleTest key={index} sampleCase={currentCase} />;
          })}
        </div>
      </div>

      <div className='flex flex-col sm:flex-row gap-5 sm:items-end justify-between mt-12'>
        <p className='text-gray-200 text-left sm:text-center'>
          This model was trained on 100,000 images from the{' '}
          <a
            href='https://www.isic-archive.com/'
            className='underline'
            target='_blank'
          >
            ISIC dataset
          </a>{' '}
        </p>
        <a
          target='_blank'
          href='https://github.com/noahbaron91/melanoma-detector'
        >
          <GitHubIcon />
        </a>
      </div>
    </div>
  );
}

export default App;

// frontend-braintumor/src/App.vue
<script setup lang="ts">
import { useTemplateRef, ref, computed } from 'vue'
import { config } from './config'
import TestImage from './components/TestImage.vue'
import { RANDOM_IMAGES, type Images } from './constants'

const inputRef = useTemplateRef('file-input')
const classification = ref<null | 0 | 1 | 2 | 3>(null)
const uploadedImageUrl = ref<null | string>(null)

const handleChange = async (event: Event) => {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (!file) return

  if (inputRef.value) inputRef.value.value = ''

  uploadedImageUrl.value = URL.createObjectURL(file)

  const formData = new FormData()
  formData.append('image', file)

  try {
    const endpoint = `${config.backendURL}/brain-tumor/predict`

    const response = await fetch(endpoint, {
      method: 'POST',
      body: formData,
    })

    const data = await response.json()

    classification.value = data.classification
  } catch (error) {
    console.error(error)
  } finally {
  }
}

const uploadImage = () => {
  inputRef.value?.click()
}

const label = computed(() => {
  if (classification.value === null) return null

  switch (classification.value) {
    case 0:
      return 'Glioma'
    case 1:
      return 'Meningioma'
    case 2:
      return 'No tumor'
    case 3:
      return 'Pituitary'
  }

  return null
})

const images = ref<Images | null>(null)

const getImages = () => {
  const imagesValues = RANDOM_IMAGES.sort(() => Math.random() - 0.5).slice(
    0,
    12,
  )
  images.value = imagesValues
}

getImages()
</script>

<template>
  <div class="header-section flex py-24 flex-col items-start px-6">
    <div class="flex flex-col gap-4 mx-auto">
      <h1
        class="text-left text-4xl md:text-5xl !leading-tight sm:text-center md:max-w-[800px]"
      >
        Detect & Classify Brain Tumors From an MRI Using AI with 79.25%
        Accuracy*
      </h1>
      <p class="text-left text-lg text-[#4D4D4D] sm:text-center">
        Trained on the
        <a
          href="https://www.kaggle.com/datasets/masoudnickparvar/brain-tumor-mri-dataset"
          class="underline"
          target="_blank"
          >Brain Tumor MRI Dataset</a
        >
      </p>
    </div>
    <div class="flex gap-2 flex-col mt-6 mx-auto" v-if="label !== null">
      <img
        v-if="uploadedImageUrl !== null"
        :src="uploadedImageUrl"
        alt="Uploaded MRI Image"
        class="h-80 w-auto rounded object-cover"
      />
      <p class="mx-auto text-xl text-black font-semibold">
        Prediction: {{ label }}
      </p>
    </div>
    <input
      type="file"
      accept="image/*"
      className="text-white invisible absolute -z-10 -top-full -left-full"
      @change="handleChange"
      ref="file-input"
    />
    <button
      @click="uploadImage"
      class="button w-full sm:w-56 md:w-80 sm:mx-auto rounded-full mt-5 bg-gray-900 text-white h-12"
    >
      Upload image
    </button>
    <p
      class="sm:text-center mx-auto mt-4 max-w-[500px] text-left text-[#4D4D4D]"
    >
      This is for educational purposes only and should not be used as a
      substitute for professional medical care
    </p>
  </div>
  <div class="flex flex-col pt-10 pb-4 px-7 mb-0">
    <div class="flex flex-col gap-4">
      <h1 class="text-3xl text-left sm:text-center sm:text-4xl">
        Test a random image
      </h1>
      <p class="text-left sm:text-center max-w-[600px] sm:mx-auto">
        Click a scan below to test the model. These images have never been seen
        by the model and are randomized. The AI model predicts the
        classification correctly on 79.25% of images.
      </p>
    </div>
    <button
      class="button w-56 rounded-full mt-5 bg-gray-900 text-white h-12 sm:mx-auto"
      @click="getImages"
    >
      Randomize Images
    </button>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-2 mt-8">
      <TestImage
        v-for="image in images"
        :correct-class="image.label"
        :file="image.file"
        :key="image.file"
      />
    </div>
    <div class="mt-6 mb-2 flex flex-col gap-3">
      <p class="text-gray-600">
        *accuracy calculated using 300 images not seen during training
      </p>
      <div>
        <div class="flex justify-between">
          <a
            href="https://github.com/nbaron1/detect-cancer"
            class="cursor-pointer"
            target="_blank"
          >
            <svg
              width="32"
              height="32"
              viewBox="0 0 32 32"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M16 2C8.265 2 2 8.265 2 16C2 22.195 6.0075 27.4275 11.5725 29.2825C12.2725 29.405 12.535 28.985 12.535 28.6175C12.535 28.285 12.5175 27.1825 12.5175 26.01C9 26.6575 8.09 25.1525 7.81 24.365C7.6525 23.9625 6.97 22.72 6.375 22.3875C5.885 22.125 5.185 21.4775 6.3575 21.46C7.46 21.4425 8.2475 22.475 8.51 22.895C9.77 25.0125 11.7825 24.4175 12.5875 24.05C12.71 23.14 13.0775 22.5275 13.48 22.1775C10.365 21.8275 7.11 20.62 7.11 15.265C7.11 13.7425 7.6525 12.4825 8.545 11.5025C8.405 11.1525 7.915 9.7175 8.685 7.7925C8.685 7.7925 9.8575 7.425 12.535 9.2275C13.655 8.9125 14.845 8.755 16.035 8.755C17.225 8.755 18.415 8.9125 19.535 9.2275C22.2125 7.4075 23.385 7.7925 23.385 7.7925C24.155 9.7175 23.665 11.1525 23.525 11.5025C24.4175 12.4825 24.96 13.725 24.96 15.265C24.96 20.6375 21.6875 21.8275 18.5725 22.1775C19.08 22.615 19.5175 23.455 19.5175 24.7675C19.5175 26.64 19.5 28.145 19.5 28.6175C19.5 28.985 19.7625 29.4225 20.4625 29.2825C23.2418 28.3443 25.6568 26.5581 27.3677 24.1753C29.0786 21.7926 29.9993 18.9334 30 16C30 8.265 23.735 2 16 2Z"
                fill="black"
              />
            </svg>
          </a>
          <p>
            built by
            <a
              class="text-gray-800 underline cursor-pointer"
              href="https://nbaron.com/"
              target="_blank"
              >nbaron</a
            >
          </p>
        </div>
      </div>
    </div>
  </div>
</template>
<style scoped>
.header-section {
  background: radial-gradient(
    50.08% 50.08% at 50% 49.92%,
    #f1f1f1 0%,
    #efefef 100%
  );
}

.button {
  background: linear-gradient(90deg, #3c3a3a 0%, #504e4e 52.5%, #3c3a3a 100%);
}
</style>
